//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Business.Erp.SupplyChain.Client.DBSservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBSservice.FileSrvSoap")]
    public interface FileSrvSoap {
        
        // CODEGEN: 参数“filebyte”需要其他方案信息，使用参数模式无法捕获这些信息。特定属性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.DBSservice.SendFileResponse SendFile(Application.Business.Erp.SupplyChain.Client.DBSservice.SendFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void DownloadFile(string fileid, string filevcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartWorkFlow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int StartWorkFlow(int flowid, string flowName, string userCode, int fileid, int filelistid);
        
        // CODEGEN: 参数“GetUserSignResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定属性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserSign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.DBSservice.GetUserSignResponse GetUserSign(Application.Business.Erp.SupplyChain.Client.DBSservice.GetUserSignRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] filebyte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fileName;
        
        public SendFileRequest() {
        }
        
        public SendFileRequest(byte[] filebyte, string fileName) {
            this.filebyte = filebyte;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] SendFileResult;
        
        public SendFileResponse() {
        }
        
        public SendFileResponse(string[] SendFileResult) {
            this.SendFileResult = SendFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserSign", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserSignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userCode;
        
        public GetUserSignRequest() {
        }
        
        public GetUserSignRequest(string userCode) {
            this.userCode = userCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserSignResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserSignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetUserSignResult;
        
        public GetUserSignResponse() {
        }
        
        public GetUserSignResponse(byte[] GetUserSignResult) {
            this.GetUserSignResult = GetUserSignResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface FileSrvSoapChannel : Application.Business.Erp.SupplyChain.Client.DBSservice.FileSrvSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class FileSrvSoapClient : System.ServiceModel.ClientBase<Application.Business.Erp.SupplyChain.Client.DBSservice.FileSrvSoap>, Application.Business.Erp.SupplyChain.Client.DBSservice.FileSrvSoap {
        
        public FileSrvSoapClient() {
        }
        
        public FileSrvSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileSrvSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileSrvSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileSrvSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Application.Business.Erp.SupplyChain.Client.DBSservice.SendFileResponse Application.Business.Erp.SupplyChain.Client.DBSservice.FileSrvSoap.SendFile(Application.Business.Erp.SupplyChain.Client.DBSservice.SendFileRequest request) {
            return base.Channel.SendFile(request);
        }
        
        public string[] SendFile(byte[] filebyte, string fileName) {
            Application.Business.Erp.SupplyChain.Client.DBSservice.SendFileRequest inValue = new Application.Business.Erp.SupplyChain.Client.DBSservice.SendFileRequest();
            inValue.filebyte = filebyte;
            inValue.fileName = fileName;
            Application.Business.Erp.SupplyChain.Client.DBSservice.SendFileResponse retVal = ((Application.Business.Erp.SupplyChain.Client.DBSservice.FileSrvSoap)(this)).SendFile(inValue);
            return retVal.SendFileResult;
        }
        
        public void DownloadFile(string fileid, string filevcode) {
            base.Channel.DownloadFile(fileid, filevcode);
        }
        
        public int StartWorkFlow(int flowid, string flowName, string userCode, int fileid, int filelistid) {
            return base.Channel.StartWorkFlow(flowid, flowName, userCode, fileid, filelistid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Application.Business.Erp.SupplyChain.Client.DBSservice.GetUserSignResponse Application.Business.Erp.SupplyChain.Client.DBSservice.FileSrvSoap.GetUserSign(Application.Business.Erp.SupplyChain.Client.DBSservice.GetUserSignRequest request) {
            return base.Channel.GetUserSign(request);
        }
        
        public byte[] GetUserSign(string userCode) {
            Application.Business.Erp.SupplyChain.Client.DBSservice.GetUserSignRequest inValue = new Application.Business.Erp.SupplyChain.Client.DBSservice.GetUserSignRequest();
            inValue.userCode = userCode;
            Application.Business.Erp.SupplyChain.Client.DBSservice.GetUserSignResponse retVal = ((Application.Business.Erp.SupplyChain.Client.DBSservice.FileSrvSoap)(this)).GetUserSign(inValue);
            return retVal.GetUserSignResult;
        }
    }
}
