//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3634
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Business.Erp.SupplyChain.Client.PLMWebServices {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://think3.com/", ConfigurationName="PLMWebServices.PLMWebServicesSoap")]
    public interface PLMWebServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/IsValidSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool IsValidSession(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void Logout(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/LoginByUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack LoginByUserInfo(out string sessionid, out string localpws, string userid, string userpwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetFilesToDownload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.FilesToTransfer GetFilesToDownload(string sessionId, string listId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/CommitDownload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CommitDownload(string sessionId, string listId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/DownloadProgress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void DownloadProgress(string sessionId, string listId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.FileToTransfer file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/StartDownload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void StartDownload(string sessionId, string listId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/CompletedDownload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CompletedDownload(string sessionId, string listId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetFilesToUpload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.FilesToTransfer GetFilesToUpload(string sessionId, string[] files);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/FilesToUpload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.FilesToTransfer FilesToUpload(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/CommitUpload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CommitUpload(string sessionId, string listId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/UploadProgress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void UploadProgress(string sessionId, string listId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.FileToTransfer file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/StartUpload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void StartUpload(string sessionId, string listId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/CompletedUpload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CompletedUpload(string sessionId, string listId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/CheckSaveData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer CheckSaveData(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/CommitSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CommitSave(string sessionId, string saveId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/RollbackSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack RollbackSave(string sessionId, string saveId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/BuildFileName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack BuildFileName(out string fileName, string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/MarkAsHaveToSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack MarkAsHaveToSave(string sessionId, string path, bool haveToSave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/MultipleMarkAsHaveToSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack MultipleMarkAsHaveToSave(string sessionId, string[] paths, bool haveToSave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/FileNewMajor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack FileNewMajor(string sessionId, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/FileNewMinor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack FileNewMinor(string sessionId, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/UndoCheckOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack UndoCheckOut(string sessionId, string[] paths);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/CheckOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CheckOut(string sessionId, string[] paths, string[] notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/CheckIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CheckIn(string sessionId, string[] paths, string[] notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/CanCheckOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CanCheckOut(out bool[] results, out ErrorStack[] errors, string sessionId, string[] paths);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/IsCheckOutByMe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack IsCheckOutByMe(out bool[] results, out ErrorStack[] errors, string sessionId, string[] paths);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/IsFileInVault", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack IsFileInVault(out bool[] results, string sessionId, string[] paths);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/UndoCheckOutByData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack UndoCheckOutByData(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/CheckOutByData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CheckOutByData(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data, string note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/CheckInByData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CheckInByData(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data, string note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/CanCheckOutByData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CanCheckOutByData(out bool[] results, out ErrorStack[] errors, string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/IsCheckOutByMeByData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack IsCheckOutByMeByData(out bool[] results, out ErrorStack[] errors, string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetEntitiesByFilter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer GetEntitiesByFilter(string sessionId, string objectType, string filter, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetChildsByParent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer GetChildsByParent(string sessionId, string parentid, string linktype, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/CreateDownloadSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer CreateDownloadSession(string sessionid, string[] stroids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetObjectInfosByObjectID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer GetObjectInfosByObjectID(string sessionId, string objectid, string[] infonames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/BuildEntityName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack BuildEntityName(out string entityName, string sessionId, string entityType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/NewMajor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer NewMajor(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/NewMinor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer NewMinor(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/Clone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer Clone(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetOwnership", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack GetOwnership(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/ReleaseOwnership", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack ReleaseOwnership(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/Exists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool Exists(string sessionId, string entityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetPropertiesPageClassName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetPropertiesPageClassName(string objectType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetQueryPageClassName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetQueryPageClassName(string objectType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetTreeViewQueryPageClassName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetTreeViewQueryPageClassName(string objectType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/IsActionNotAllowed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool IsActionNotAllowed(string sessionId, string entityId, string action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetEntities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GetEntities(string entityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetLinkTypeEntities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GetLinkTypeEntities(string entityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetCaption", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetCaption(string name, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/DeleteEntities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack DeleteEntities(string entityTypeName, string sessionId, string[] listId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/AutoLoginByUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack AutoLoginByUserInfo(out string sessionid, out string localpws, string userName, string jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/AddDocumentByCustom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack AddDocumentByCustom(out string[] listFileIds, object[] listFileBytes, string[] fileNames, string documentObjectType, string saveMode, DictionaryObjectInfo[] dicKeyValue, string sessionid, string userName, string jobId, string localVault);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/UpdateDocumentByCustom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack UpdateDocumentByCustom(string[] listFileIds, string documentObjectType, object[] listFileBytes, string[] fileNames, string updateMode, DictionaryObjectInfo[] dicKeyValue, string sessionid, string userName, string jobId, string localVault);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/DownLoadDocumentByCustom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack DownLoadDocumentByCustom(out object[] listFileBytes, out string[] listFileNames, string[] listFileIds, string sessionid, string userName, string jobId, string localVault);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/DeleteDocumentByCustom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack DeleteDocumentByCustom(string[] listFileIds, string deleteMode, string sessionid, string userName, string jobId, string localVault);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/AddDocumentByCustomExtend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack AddDocumentByCustomExtend(out ProjectDocument[] listResult, ProjectDocument[] listDocument, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DocumentSaveMode saveMode, string sessionid, string userName, string jobId, string localVault);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/DownLoadDocumentByCustomExtend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack DownLoadDocumentByCustomExtend(out ProjectDocument[] listResult, ProjectDocument[] listDocument, string sessionid, string userName, string jobId, string localVault);
        
        // CODEGEN: 参数“docInfoTypeQuery”需要其他方案信息，使用参数模式无法捕获这些信息。特定属性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetProjectDocumentByCustomExtend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.GetProjectDocumentByCustomExtendResponse GetProjectDocumentByCustomExtend(Application.Business.Erp.SupplyChain.Client.PLMWebServices.GetProjectDocumentByCustomExtendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetProjectDocumentByDocumentId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack GetProjectDocumentByDocumentId(out ProjectDocument[] listResult, string[] fileIds, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DocumentQueryVersion queryMode, string sessionid, string userName, string jobId, string localVault);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/UpdateDocumentByCustomExtend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack UpdateDocumentByCustomExtend(out ProjectDocument[] listResult, ProjectDocument[] listDocument, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DocumentUpdateMode updateMode, string sessionid, string userName, string jobId, string localVault);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/DeleteDocumentByCustomExtend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack DeleteDocumentByCustomExtend(ProjectDocument[] listDocument, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DocumentDeleteMode deleteMode, string sessionid, string userName, string jobId, string localVault);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetCategoryByCustomExtend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack GetCategoryByCustomExtend(out CategoryNode[] listResult, string CategoryTypeName, Application.Business.Erp.SupplyChain.Client.PLMWebServices.CategoryQueryModeEnum queryMode, string queryKeyWords, string sessionid, string userName, string jobId, string localVault);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetCustomNameSerializableInfos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetCustomNameSerializableInfos(string type, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetObjectTypeSerializableInfos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetObjectTypeSerializableInfos(string type, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetSerializableInfos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetSerializableInfos(string type, string environment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/CheckObjectType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string CheckObjectType(string rootTypeName, string typeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/ReloadUserXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void ReloadUserXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/CreateTxtFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string CreateTxtFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/DeleteFileName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void DeleteFileName(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/ReadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string ReadFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/WriteFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void WriteFile(string fileName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://think3.com/")]
    public partial class ErrorStack : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string messageField;
        
        private string stackDumpField;
        
        private string detailsField;
        
        private string suggestionsField;
        
        private string seeAlsoField;
        
        private ErrorStack innerErrorStackField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StackDump {
            get {
                return this.stackDumpField;
            }
            set {
                this.stackDumpField = value;
                this.RaisePropertyChanged("StackDump");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("Details");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Suggestions {
            get {
                return this.suggestionsField;
            }
            set {
                this.suggestionsField = value;
                this.RaisePropertyChanged("Suggestions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SeeAlso {
            get {
                return this.seeAlsoField;
            }
            set {
                this.seeAlsoField = value;
                this.RaisePropertyChanged("SeeAlso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ErrorStack InnerErrorStack {
            get {
                return this.innerErrorStackField;
            }
            set {
                this.innerErrorStackField = value;
                this.RaisePropertyChanged("InnerErrorStack");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://think3.com/")]
    public partial class CategoryNode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityIDField;
        
        private string categoryCodeField;
        
        private string categoryNameField;
        
        private string categoryDescField;
        
        private string categorySysCodeField;
        
        private string categoryIDSysCodeField;
        
        private int categoryLevelField;
        
        private int orderNoField;
        
        private string ownerIDField;
        
        private string ownerNameField;
        
        private string ownerOrgSysCodeField;
        
        private CategoryNode parentNodeField;
        
        private System.DateTime createTimeField;
        
        private System.DateTime updateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntityID {
            get {
                return this.entityIDField;
            }
            set {
                this.entityIDField = value;
                this.RaisePropertyChanged("EntityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CategoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
                this.RaisePropertyChanged("CategoryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CategoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
                this.RaisePropertyChanged("CategoryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CategoryDesc {
            get {
                return this.categoryDescField;
            }
            set {
                this.categoryDescField = value;
                this.RaisePropertyChanged("CategoryDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CategorySysCode {
            get {
                return this.categorySysCodeField;
            }
            set {
                this.categorySysCodeField = value;
                this.RaisePropertyChanged("CategorySysCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CategoryIDSysCode {
            get {
                return this.categoryIDSysCodeField;
            }
            set {
                this.categoryIDSysCodeField = value;
                this.RaisePropertyChanged("CategoryIDSysCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int CategoryLevel {
            get {
                return this.categoryLevelField;
            }
            set {
                this.categoryLevelField = value;
                this.RaisePropertyChanged("CategoryLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("OrderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string OwnerID {
            get {
                return this.ownerIDField;
            }
            set {
                this.ownerIDField = value;
                this.RaisePropertyChanged("OwnerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string OwnerName {
            get {
                return this.ownerNameField;
            }
            set {
                this.ownerNameField = value;
                this.RaisePropertyChanged("OwnerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string OwnerOrgSysCode {
            get {
                return this.ownerOrgSysCodeField;
            }
            set {
                this.ownerOrgSysCodeField = value;
                this.RaisePropertyChanged("OwnerOrgSysCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public CategoryNode ParentNode {
            get {
                return this.parentNodeField;
            }
            set {
                this.parentNodeField = value;
                this.RaisePropertyChanged("ParentNode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
                this.RaisePropertyChanged("CreateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime UpdateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
                this.RaisePropertyChanged("UpdateTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://think3.com/")]
    public partial class ProjectDocument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string entityIDField;
        
        private byte[] fileDataByteField;
        
        private string projectNameField;
        
        private string projectCodeField;
        
        private string objectTypeNameField;
        
        private string categoryRelaDocTypeField;
        
        private CategoryNode categoryField;
        
        private DocumentInfoType docTypeField;
        
        private string fileNameField;
        
        private string extendNameField;
        
        private string codeField;
        
        private string nameField;
        
        private string titleField;
        
        private string authorField;
        
        private string keyWordsField;
        
        private string descriptionField;
        
        private string versionField;
        
        private string revisionField;
        
        private DocumentState stateField;
        
        private string ownerIDField;
        
        private string ownerNameField;
        
        private string ownerOrgSysCodeField;
        
        private System.DateTime createTimeField;
        
        private System.DateTime updateTimeField;
        
        private bool isInspectionLotField;
        
        private string[] extendInfoNamesField;
        
        private object[] extendInfoValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EntityID {
            get {
                return this.entityIDField;
            }
            set {
                this.entityIDField = value;
                this.RaisePropertyChanged("EntityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] FileDataByte {
            get {
                return this.fileDataByteField;
            }
            set {
                this.fileDataByteField = value;
                this.RaisePropertyChanged("FileDataByte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ProjectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
                this.RaisePropertyChanged("ProjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ProjectCode {
            get {
                return this.projectCodeField;
            }
            set {
                this.projectCodeField = value;
                this.RaisePropertyChanged("ProjectCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ObjectTypeName {
            get {
                return this.objectTypeNameField;
            }
            set {
                this.objectTypeNameField = value;
                this.RaisePropertyChanged("ObjectTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CategoryRelaDocType {
            get {
                return this.categoryRelaDocTypeField;
            }
            set {
                this.categoryRelaDocTypeField = value;
                this.RaisePropertyChanged("CategoryRelaDocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public CategoryNode Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public DocumentInfoType DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ExtendName {
            get {
                return this.extendNameField;
            }
            set {
                this.extendNameField = value;
                this.RaisePropertyChanged("ExtendName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("Author");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string KeyWords {
            get {
                return this.keyWordsField;
            }
            set {
                this.keyWordsField = value;
                this.RaisePropertyChanged("KeyWords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
                this.RaisePropertyChanged("Revision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public DocumentState State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string OwnerID {
            get {
                return this.ownerIDField;
            }
            set {
                this.ownerIDField = value;
                this.RaisePropertyChanged("OwnerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string OwnerName {
            get {
                return this.ownerNameField;
            }
            set {
                this.ownerNameField = value;
                this.RaisePropertyChanged("OwnerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string OwnerOrgSysCode {
            get {
                return this.ownerOrgSysCodeField;
            }
            set {
                this.ownerOrgSysCodeField = value;
                this.RaisePropertyChanged("OwnerOrgSysCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
                this.RaisePropertyChanged("CreateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public System.DateTime UpdateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
                this.RaisePropertyChanged("UpdateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public bool IsInspectionLot {
            get {
                return this.isInspectionLotField;
            }
            set {
                this.isInspectionLotField = value;
                this.RaisePropertyChanged("IsInspectionLot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=26)]
        public string[] ExtendInfoNames {
            get {
                return this.extendInfoNamesField;
            }
            set {
                this.extendInfoNamesField = value;
                this.RaisePropertyChanged("ExtendInfoNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=27)]
        public object[] ExtendInfoValues {
            get {
                return this.extendInfoValuesField;
            }
            set {
                this.extendInfoValuesField = value;
                this.RaisePropertyChanged("ExtendInfoValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://think3.com/")]
    public enum DocumentInfoType {
        
        /// <remarks/>
        文本,
        
        /// <remarks/>
        图片,
        
        /// <remarks/>
        音频,
        
        /// <remarks/>
        视频,
        
        /// <remarks/>
        信息模型,
        
        /// <remarks/>
        程序,
        
        /// <remarks/>
        普通文档,
        
        /// <remarks/>
        合同,
        
        /// <remarks/>
        技术文档,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://think3.com/")]
    public enum DocumentState {
        
        /// <remarks/>
        编制,
        
        /// <remarks/>
        提交,
        
        /// <remarks/>
        发布,
        
        /// <remarks/>
        作废,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://think3.com/")]
    public partial class DictionaryObjectInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] infoNamesField;
        
        private object[] infoValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] InfoNames {
            get {
                return this.infoNamesField;
            }
            set {
                this.infoNamesField = value;
                this.RaisePropertyChanged("InfoNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public object[] InfoValues {
            get {
                return this.infoValuesField;
            }
            set {
                this.infoValuesField = value;
                this.RaisePropertyChanged("InfoValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://think3.com/")]
    public partial class DataToTransfer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xmlContentsField;
        
        private string uniqueIdField;
        
        private ErrorStack errorStackField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string XmlContents {
            get {
                return this.xmlContentsField;
            }
            set {
                this.xmlContentsField = value;
                this.RaisePropertyChanged("XmlContents");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UniqueId {
            get {
                return this.uniqueIdField;
            }
            set {
                this.uniqueIdField = value;
                this.RaisePropertyChanged("UniqueId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ErrorStack ErrorStack {
            get {
                return this.errorStackField;
            }
            set {
                this.errorStackField = value;
                this.RaisePropertyChanged("ErrorStack");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://think3.com/")]
    public partial class FileToTransfer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isSavedField;
        
        private string nameIDField;
        
        private string objectIDField;
        
        private int versionField;
        
        private string privateWorkspaceFileField;
        
        private string privateVOBFileField;
        
        private string partialUriField;
        
        private string baseUriField;
        
        private string userField;
        
        private string passwordField;
        
        private string domainField;
        
        private string stateField;
        
        private ErrorStack errorStackField;
        
        private bool canUploadField;
        
        private bool haveToDownloadField;
        
        private bool auxiliaryField;
        
        private bool cancelledField;
        
        private long lengthField;
        
        private string elapsedTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsSaved {
            get {
                return this.isSavedField;
            }
            set {
                this.isSavedField = value;
                this.RaisePropertyChanged("IsSaved");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NameID {
            get {
                return this.nameIDField;
            }
            set {
                this.nameIDField = value;
                this.RaisePropertyChanged("NameID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ObjectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
                this.RaisePropertyChanged("ObjectID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PrivateWorkspaceFile {
            get {
                return this.privateWorkspaceFileField;
            }
            set {
                this.privateWorkspaceFileField = value;
                this.RaisePropertyChanged("PrivateWorkspaceFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PrivateVOBFile {
            get {
                return this.privateVOBFileField;
            }
            set {
                this.privateVOBFileField = value;
                this.RaisePropertyChanged("PrivateVOBFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PartialUri {
            get {
                return this.partialUriField;
            }
            set {
                this.partialUriField = value;
                this.RaisePropertyChanged("PartialUri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BaseUri {
            get {
                return this.baseUriField;
            }
            set {
                this.baseUriField = value;
                this.RaisePropertyChanged("BaseUri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
                this.RaisePropertyChanged("Domain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public ErrorStack ErrorStack {
            get {
                return this.errorStackField;
            }
            set {
                this.errorStackField = value;
                this.RaisePropertyChanged("ErrorStack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool CanUpload {
            get {
                return this.canUploadField;
            }
            set {
                this.canUploadField = value;
                this.RaisePropertyChanged("CanUpload");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool HaveToDownload {
            get {
                return this.haveToDownloadField;
            }
            set {
                this.haveToDownloadField = value;
                this.RaisePropertyChanged("HaveToDownload");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool Auxiliary {
            get {
                return this.auxiliaryField;
            }
            set {
                this.auxiliaryField = value;
                this.RaisePropertyChanged("Auxiliary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool Cancelled {
            get {
                return this.cancelledField;
            }
            set {
                this.cancelledField = value;
                this.RaisePropertyChanged("Cancelled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public long Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("Length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ElapsedTime {
            get {
                return this.elapsedTimeField;
            }
            set {
                this.elapsedTimeField = value;
                this.RaisePropertyChanged("ElapsedTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://think3.com/")]
    public partial class FilesToTransfer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ErrorStack errorStackField;
        
        private string listIdField;
        
        private FileToTransfer[] filesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ErrorStack ErrorStack {
            get {
                return this.errorStackField;
            }
            set {
                this.errorStackField = value;
                this.RaisePropertyChanged("ErrorStack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ListId {
            get {
                return this.listIdField;
            }
            set {
                this.listIdField = value;
                this.RaisePropertyChanged("ListId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public FileToTransfer[] Files {
            get {
                return this.filesField;
            }
            set {
                this.filesField = value;
                this.RaisePropertyChanged("Files");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://think3.com/")]
    public enum DocumentSaveMode {
        
        /// <remarks/>
        一个文件生成一个文档对象,
        
        /// <remarks/>
        所有文件生成一个文档对象,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://think3.com/")]
    public enum DocumentQueryVersion {
        
        /// <remarks/>
        最新版本,
        
        /// <remarks/>
        所有版本,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProjectDocumentByCustomExtend", WrapperNamespace="http://think3.com/", IsWrapped=true)]
    public partial class GetProjectDocumentByCustomExtendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=0)]
        public string projectCodeQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=1)]
        public string projectNameQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=2)]
        public string docCodeQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=3)]
        public string docNameQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=4)]
        public string docExtendNameQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<DocumentInfoType> docInfoTypeQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=6)]
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.DocumentQueryVersion queryMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=7)]
        public string docVersionQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=8)]
        public string docRevisionQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> docCreateBeginTimeQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> docCreateEndTimeQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=11)]
        public string docOwnerQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<DocumentState> docStateQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=13)]
        public string docKeyWordQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=14)]
        public string sessionid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=15)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=16)]
        public string jobId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=17)]
        public string localVault;
        
        public GetProjectDocumentByCustomExtendRequest() {
        }
        
        public GetProjectDocumentByCustomExtendRequest(
                    string projectCodeQuery, 
                    string projectNameQuery, 
                    string docCodeQuery, 
                    string docNameQuery, 
                    string docExtendNameQuery, 
                    System.Nullable<DocumentInfoType> docInfoTypeQuery, 
                    Application.Business.Erp.SupplyChain.Client.PLMWebServices.DocumentQueryVersion queryMode, 
                    string docVersionQuery, 
                    string docRevisionQuery, 
                    System.Nullable<System.DateTime> docCreateBeginTimeQuery, 
                    System.Nullable<System.DateTime> docCreateEndTimeQuery, 
                    string docOwnerQuery, 
                    System.Nullable<DocumentState> docStateQuery, 
                    string docKeyWordQuery, 
                    string sessionid, 
                    string userName, 
                    string jobId, 
                    string localVault) {
            this.projectCodeQuery = projectCodeQuery;
            this.projectNameQuery = projectNameQuery;
            this.docCodeQuery = docCodeQuery;
            this.docNameQuery = docNameQuery;
            this.docExtendNameQuery = docExtendNameQuery;
            this.docInfoTypeQuery = docInfoTypeQuery;
            this.queryMode = queryMode;
            this.docVersionQuery = docVersionQuery;
            this.docRevisionQuery = docRevisionQuery;
            this.docCreateBeginTimeQuery = docCreateBeginTimeQuery;
            this.docCreateEndTimeQuery = docCreateEndTimeQuery;
            this.docOwnerQuery = docOwnerQuery;
            this.docStateQuery = docStateQuery;
            this.docKeyWordQuery = docKeyWordQuery;
            this.sessionid = sessionid;
            this.userName = userName;
            this.jobId = jobId;
            this.localVault = localVault;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProjectDocumentByCustomExtendResponse", WrapperNamespace="http://think3.com/", IsWrapped=true)]
    public partial class GetProjectDocumentByCustomExtendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=0)]
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack GetProjectDocumentByCustomExtendResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://think3.com/", Order=1)]
        public ProjectDocument[] listResult;
        
        public GetProjectDocumentByCustomExtendResponse() {
        }
        
        public GetProjectDocumentByCustomExtendResponse(Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack GetProjectDocumentByCustomExtendResult, ProjectDocument[] listResult) {
            this.GetProjectDocumentByCustomExtendResult = GetProjectDocumentByCustomExtendResult;
            this.listResult = listResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://think3.com/")]
    public enum DocumentUpdateMode {
        
        /// <remarks/>
        添加一个新版次文件,
        
        /// <remarks/>
        覆盖原有最新版次文件,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://think3.com/")]
    public enum DocumentDeleteMode {
        
        /// <remarks/>
        删除最新版本,
        
        /// <remarks/>
        删除所有版本,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://think3.com/")]
    public enum CategoryQueryModeEnum {
        
        /// <remarks/>
        树方式,
        
        /// <remarks/>
        表方式,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface PLMWebServicesSoapChannel : Application.Business.Erp.SupplyChain.Client.PLMWebServices.PLMWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PLMWebServicesSoapClient : System.ServiceModel.ClientBase<Application.Business.Erp.SupplyChain.Client.PLMWebServices.PLMWebServicesSoap>, Application.Business.Erp.SupplyChain.Client.PLMWebServices.PLMWebServicesSoap {
        
        public PLMWebServicesSoapClient() {
        }
        
        public PLMWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PLMWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PLMWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PLMWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsValidSession(string sessionId) {
            return base.Channel.IsValidSession(sessionId);
        }
        
        public void Logout(string sessionId) {
            base.Channel.Logout(sessionId);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack LoginByUserInfo(out string sessionid, out string localpws, string userid, string userpwd) {
            return base.Channel.LoginByUserInfo(out sessionid, out localpws, userid, userpwd);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.FilesToTransfer GetFilesToDownload(string sessionId, string listId) {
            return base.Channel.GetFilesToDownload(sessionId, listId);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CommitDownload(string sessionId, string listId) {
            return base.Channel.CommitDownload(sessionId, listId);
        }
        
        public void DownloadProgress(string sessionId, string listId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.FileToTransfer file) {
            base.Channel.DownloadProgress(sessionId, listId, file);
        }
        
        public void StartDownload(string sessionId, string listId) {
            base.Channel.StartDownload(sessionId, listId);
        }
        
        public void CompletedDownload(string sessionId, string listId) {
            base.Channel.CompletedDownload(sessionId, listId);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.FilesToTransfer GetFilesToUpload(string sessionId, string[] files) {
            return base.Channel.GetFilesToUpload(sessionId, files);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.FilesToTransfer FilesToUpload(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data) {
            return base.Channel.FilesToUpload(sessionId, data);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CommitUpload(string sessionId, string listId) {
            return base.Channel.CommitUpload(sessionId, listId);
        }
        
        public void UploadProgress(string sessionId, string listId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.FileToTransfer file) {
            base.Channel.UploadProgress(sessionId, listId, file);
        }
        
        public void StartUpload(string sessionId, string listId) {
            base.Channel.StartUpload(sessionId, listId);
        }
        
        public void CompletedUpload(string sessionId, string listId) {
            base.Channel.CompletedUpload(sessionId, listId);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer CheckSaveData(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data) {
            return base.Channel.CheckSaveData(sessionId, data);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CommitSave(string sessionId, string saveId) {
            return base.Channel.CommitSave(sessionId, saveId);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack RollbackSave(string sessionId, string saveId) {
            return base.Channel.RollbackSave(sessionId, saveId);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack BuildFileName(out string fileName, string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data) {
            return base.Channel.BuildFileName(out fileName, sessionId, data);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack MarkAsHaveToSave(string sessionId, string path, bool haveToSave) {
            return base.Channel.MarkAsHaveToSave(sessionId, path, haveToSave);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack MultipleMarkAsHaveToSave(string sessionId, string[] paths, bool haveToSave) {
            return base.Channel.MultipleMarkAsHaveToSave(sessionId, paths, haveToSave);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack FileNewMajor(string sessionId, string path) {
            return base.Channel.FileNewMajor(sessionId, path);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack FileNewMinor(string sessionId, string path) {
            return base.Channel.FileNewMinor(sessionId, path);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack UndoCheckOut(string sessionId, string[] paths) {
            return base.Channel.UndoCheckOut(sessionId, paths);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CheckOut(string sessionId, string[] paths, string[] notes) {
            return base.Channel.CheckOut(sessionId, paths, notes);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CheckIn(string sessionId, string[] paths, string[] notes) {
            return base.Channel.CheckIn(sessionId, paths, notes);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CanCheckOut(out bool[] results, out ErrorStack[] errors, string sessionId, string[] paths) {
            return base.Channel.CanCheckOut(out results, out errors, sessionId, paths);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack IsCheckOutByMe(out bool[] results, out ErrorStack[] errors, string sessionId, string[] paths) {
            return base.Channel.IsCheckOutByMe(out results, out errors, sessionId, paths);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack IsFileInVault(out bool[] results, string sessionId, string[] paths) {
            return base.Channel.IsFileInVault(out results, sessionId, paths);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack UndoCheckOutByData(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data) {
            return base.Channel.UndoCheckOutByData(sessionId, data);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CheckOutByData(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data, string note) {
            return base.Channel.CheckOutByData(sessionId, data, note);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CheckInByData(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data, string note) {
            return base.Channel.CheckInByData(sessionId, data, note);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack CanCheckOutByData(out bool[] results, out ErrorStack[] errors, string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data) {
            return base.Channel.CanCheckOutByData(out results, out errors, sessionId, data);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack IsCheckOutByMeByData(out bool[] results, out ErrorStack[] errors, string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data) {
            return base.Channel.IsCheckOutByMeByData(out results, out errors, sessionId, data);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer GetEntitiesByFilter(string sessionId, string objectType, string filter, string environment) {
            return base.Channel.GetEntitiesByFilter(sessionId, objectType, filter, environment);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer GetChildsByParent(string sessionId, string parentid, string linktype, string environment) {
            return base.Channel.GetChildsByParent(sessionId, parentid, linktype, environment);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer CreateDownloadSession(string sessionid, string[] stroids) {
            return base.Channel.CreateDownloadSession(sessionid, stroids);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer GetObjectInfosByObjectID(string sessionId, string objectid, string[] infonames) {
            return base.Channel.GetObjectInfosByObjectID(sessionId, objectid, infonames);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack BuildEntityName(out string entityName, string sessionId, string entityType) {
            return base.Channel.BuildEntityName(out entityName, sessionId, entityType);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer NewMajor(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data) {
            return base.Channel.NewMajor(sessionId, data);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer NewMinor(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data) {
            return base.Channel.NewMinor(sessionId, data);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer Clone(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data) {
            return base.Channel.Clone(sessionId, data);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack GetOwnership(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data) {
            return base.Channel.GetOwnership(sessionId, data);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack ReleaseOwnership(string sessionId, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DataToTransfer data) {
            return base.Channel.ReleaseOwnership(sessionId, data);
        }
        
        public bool Exists(string sessionId, string entityId) {
            return base.Channel.Exists(sessionId, entityId);
        }
        
        public string GetPropertiesPageClassName(string objectType) {
            return base.Channel.GetPropertiesPageClassName(objectType);
        }
        
        public string GetQueryPageClassName(string objectType) {
            return base.Channel.GetQueryPageClassName(objectType);
        }
        
        public string GetTreeViewQueryPageClassName(string objectType) {
            return base.Channel.GetTreeViewQueryPageClassName(objectType);
        }
        
        public bool IsActionNotAllowed(string sessionId, string entityId, string action) {
            return base.Channel.IsActionNotAllowed(sessionId, entityId, action);
        }
        
        public System.Data.DataTable GetEntities(string entityName) {
            return base.Channel.GetEntities(entityName);
        }
        
        public System.Data.DataTable GetLinkTypeEntities(string entityName) {
            return base.Channel.GetLinkTypeEntities(entityName);
        }
        
        public string GetCaption(string name, string language) {
            return base.Channel.GetCaption(name, language);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack DeleteEntities(string entityTypeName, string sessionId, string[] listId) {
            return base.Channel.DeleteEntities(entityTypeName, sessionId, listId);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack AutoLoginByUserInfo(out string sessionid, out string localpws, string userName, string jobId) {
            return base.Channel.AutoLoginByUserInfo(out sessionid, out localpws, userName, jobId);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack AddDocumentByCustom(out string[] listFileIds, object[] listFileBytes, string[] fileNames, string documentObjectType, string saveMode, DictionaryObjectInfo[] dicKeyValue, string sessionid, string userName, string jobId, string localVault) {
            return base.Channel.AddDocumentByCustom(out listFileIds, listFileBytes, fileNames, documentObjectType, saveMode, dicKeyValue, sessionid, userName, jobId, localVault);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack UpdateDocumentByCustom(string[] listFileIds, string documentObjectType, object[] listFileBytes, string[] fileNames, string updateMode, DictionaryObjectInfo[] dicKeyValue, string sessionid, string userName, string jobId, string localVault) {
            return base.Channel.UpdateDocumentByCustom(listFileIds, documentObjectType, listFileBytes, fileNames, updateMode, dicKeyValue, sessionid, userName, jobId, localVault);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack DownLoadDocumentByCustom(out object[] listFileBytes, out string[] listFileNames, string[] listFileIds, string sessionid, string userName, string jobId, string localVault) {
            return base.Channel.DownLoadDocumentByCustom(out listFileBytes, out listFileNames, listFileIds, sessionid, userName, jobId, localVault);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack DeleteDocumentByCustom(string[] listFileIds, string deleteMode, string sessionid, string userName, string jobId, string localVault) {
            return base.Channel.DeleteDocumentByCustom(listFileIds, deleteMode, sessionid, userName, jobId, localVault);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack AddDocumentByCustomExtend(out ProjectDocument[] listResult, ProjectDocument[] listDocument, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DocumentSaveMode saveMode, string sessionid, string userName, string jobId, string localVault) {
            return base.Channel.AddDocumentByCustomExtend(out listResult, listDocument, saveMode, sessionid, userName, jobId, localVault);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack DownLoadDocumentByCustomExtend(out ProjectDocument[] listResult, ProjectDocument[] listDocument, string sessionid, string userName, string jobId, string localVault) {
            return base.Channel.DownLoadDocumentByCustomExtend(out listResult, listDocument, sessionid, userName, jobId, localVault);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Application.Business.Erp.SupplyChain.Client.PLMWebServices.GetProjectDocumentByCustomExtendResponse Application.Business.Erp.SupplyChain.Client.PLMWebServices.PLMWebServicesSoap.GetProjectDocumentByCustomExtend(Application.Business.Erp.SupplyChain.Client.PLMWebServices.GetProjectDocumentByCustomExtendRequest request) {
            return base.Channel.GetProjectDocumentByCustomExtend(request);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack GetProjectDocumentByCustomExtend(
                    string projectCodeQuery, 
                    string projectNameQuery, 
                    string docCodeQuery, 
                    string docNameQuery, 
                    string docExtendNameQuery, 
                    System.Nullable<DocumentInfoType> docInfoTypeQuery, 
                    Application.Business.Erp.SupplyChain.Client.PLMWebServices.DocumentQueryVersion queryMode, 
                    string docVersionQuery, 
                    string docRevisionQuery, 
                    System.Nullable<System.DateTime> docCreateBeginTimeQuery, 
                    System.Nullable<System.DateTime> docCreateEndTimeQuery, 
                    string docOwnerQuery, 
                    System.Nullable<DocumentState> docStateQuery, 
                    string docKeyWordQuery, 
                    string sessionid, 
                    string userName, 
                    string jobId, 
                    string localVault, 
                    out ProjectDocument[] listResult) {
            Application.Business.Erp.SupplyChain.Client.PLMWebServices.GetProjectDocumentByCustomExtendRequest inValue = new Application.Business.Erp.SupplyChain.Client.PLMWebServices.GetProjectDocumentByCustomExtendRequest();
            inValue.projectCodeQuery = projectCodeQuery;
            inValue.projectNameQuery = projectNameQuery;
            inValue.docCodeQuery = docCodeQuery;
            inValue.docNameQuery = docNameQuery;
            inValue.docExtendNameQuery = docExtendNameQuery;
            inValue.docInfoTypeQuery = docInfoTypeQuery;
            inValue.queryMode = queryMode;
            inValue.docVersionQuery = docVersionQuery;
            inValue.docRevisionQuery = docRevisionQuery;
            inValue.docCreateBeginTimeQuery = docCreateBeginTimeQuery;
            inValue.docCreateEndTimeQuery = docCreateEndTimeQuery;
            inValue.docOwnerQuery = docOwnerQuery;
            inValue.docStateQuery = docStateQuery;
            inValue.docKeyWordQuery = docKeyWordQuery;
            inValue.sessionid = sessionid;
            inValue.userName = userName;
            inValue.jobId = jobId;
            inValue.localVault = localVault;
            Application.Business.Erp.SupplyChain.Client.PLMWebServices.GetProjectDocumentByCustomExtendResponse retVal = ((Application.Business.Erp.SupplyChain.Client.PLMWebServices.PLMWebServicesSoap)(this)).GetProjectDocumentByCustomExtend(inValue);
            listResult = retVal.listResult;
            return retVal.GetProjectDocumentByCustomExtendResult;
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack GetProjectDocumentByDocumentId(out ProjectDocument[] listResult, string[] fileIds, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DocumentQueryVersion queryMode, string sessionid, string userName, string jobId, string localVault) {
            return base.Channel.GetProjectDocumentByDocumentId(out listResult, fileIds, queryMode, sessionid, userName, jobId, localVault);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack UpdateDocumentByCustomExtend(out ProjectDocument[] listResult, ProjectDocument[] listDocument, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DocumentUpdateMode updateMode, string sessionid, string userName, string jobId, string localVault) {
            return base.Channel.UpdateDocumentByCustomExtend(out listResult, listDocument, updateMode, sessionid, userName, jobId, localVault);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack DeleteDocumentByCustomExtend(ProjectDocument[] listDocument, Application.Business.Erp.SupplyChain.Client.PLMWebServices.DocumentDeleteMode deleteMode, string sessionid, string userName, string jobId, string localVault) {
            return base.Channel.DeleteDocumentByCustomExtend(listDocument, deleteMode, sessionid, userName, jobId, localVault);
        }
        
        public Application.Business.Erp.SupplyChain.Client.PLMWebServices.ErrorStack GetCategoryByCustomExtend(out CategoryNode[] listResult, string CategoryTypeName, Application.Business.Erp.SupplyChain.Client.PLMWebServices.CategoryQueryModeEnum queryMode, string queryKeyWords, string sessionid, string userName, string jobId, string localVault) {
            return base.Channel.GetCategoryByCustomExtend(out listResult, CategoryTypeName, queryMode, queryKeyWords, sessionid, userName, jobId, localVault);
        }
        
        public string GetCustomNameSerializableInfos(string type, string environment) {
            return base.Channel.GetCustomNameSerializableInfos(type, environment);
        }
        
        public string GetObjectTypeSerializableInfos(string type, string environment) {
            return base.Channel.GetObjectTypeSerializableInfos(type, environment);
        }
        
        public string GetSerializableInfos(string type, string environment) {
            return base.Channel.GetSerializableInfos(type, environment);
        }
        
        public string CheckObjectType(string rootTypeName, string typeName) {
            return base.Channel.CheckObjectType(rootTypeName, typeName);
        }
        
        public void ReloadUserXML() {
            base.Channel.ReloadUserXML();
        }
        
        public string CreateTxtFile() {
            return base.Channel.CreateTxtFile();
        }
        
        public void DeleteFileName(string fileName) {
            base.Channel.DeleteFileName(fileName);
        }
        
        public string ReadFile(string fileName) {
            return base.Channel.ReadFile(fileName);
        }
        
        public void WriteFile(string fileName) {
            base.Channel.WriteFile(fileName);
        }
    }
}
