//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5477
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalIntegrationConsole.KBOrgUserSyncDataSrv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpeOrg", Namespace="http://think3.com/")]
    [System.SerializableAttribute()]
    public partial class OpeOrg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentOrgCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OrgCode {
            get {
                return this.OrgCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgCodeField, value) != true)) {
                    this.OrgCodeField = value;
                    this.RaisePropertyChanged("OrgCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OrgName {
            get {
                return this.OrgNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgNameField, value) != true)) {
                    this.OrgNameField = value;
                    this.RaisePropertyChanged("OrgName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OrgType {
            get {
                return this.OrgTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgTypeField, value) != true)) {
                    this.OrgTypeField = value;
                    this.RaisePropertyChanged("OrgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ParentOrgCode {
            get {
                return this.ParentOrgCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentOrgCodeField, value) != true)) {
                    this.ParentOrgCodeField = value;
                    this.RaisePropertyChanged("ParentOrgCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetOb", Namespace="http://think3.com/")]
    [System.SerializableAttribute()]
    public partial class RetOb : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        private int Out0Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Out0 {
            get {
                return this.Out0Field;
            }
            set {
                if ((this.Out0Field.Equals(value) != true)) {
                    this.Out0Field = value;
                    this.RaisePropertyChanged("Out0");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://think3.com/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserCode {
            get {
                return this.UserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCodeField, value) != true)) {
                    this.UserCodeField = value;
                    this.RaisePropertyChanged("UserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Post", Namespace="http://think3.com/")]
    [System.SerializableAttribute()]
    public partial class Post : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosiCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosiNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgCodeField;
        
        private int OrderNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PosiCode {
            get {
                return this.PosiCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PosiCodeField, value) != true)) {
                    this.PosiCodeField = value;
                    this.RaisePropertyChanged("PosiCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PosiName {
            get {
                return this.PosiNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PosiNameField, value) != true)) {
                    this.PosiNameField = value;
                    this.RaisePropertyChanged("PosiName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OrgCode {
            get {
                return this.OrgCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgCodeField, value) != true)) {
                    this.OrgCodeField = value;
                    this.RaisePropertyChanged("OrgCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int OrderNo {
            get {
                return this.OrderNoField;
            }
            set {
                if ((this.OrderNoField.Equals(value) != true)) {
                    this.OrderNoField = value;
                    this.RaisePropertyChanged("OrderNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://think3.com/")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RoleCode {
            get {
                return this.RoleCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleCodeField, value) != true)) {
                    this.RoleCodeField = value;
                    this.RaisePropertyChanged("RoleCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://think3.com/", ConfigurationName="KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap")]
    public interface OrgUserSyncDataSrvSoap {
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 parentOrgCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/AddOrg", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddOrgResponse AddOrg(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddOrgRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 org 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/UpdateOrg", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateOrgResponse UpdateOrg(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateOrgRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 org 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/DeleteOrg", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteOrgResponse DeleteOrg(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteOrgRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 orgCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/SetOrgInfo", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.SetOrgInfoResponse SetOrgInfo(PortalIntegrationConsole.KBOrgUserSyncDataSrv.SetOrgInfoRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 orgCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetOrgByCode", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetOrgByCodeResponse GetOrgByCode(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetOrgByCodeRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 user 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/AddUser", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddUserResponse AddUser(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddUserRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 user 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/UpdateUser", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateUserResponse UpdateUser(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateUserRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 userCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/DeleteUser", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteUserResponse DeleteUser(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteUserRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 userCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetUserByCode", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetUserByCodeResponse GetUserByCode(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetUserByCodeRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 emps 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/UpdateEmpPost", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpPostResponse UpdateEmpPost(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpPostRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 orgCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/AddPost", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddPostResponse AddPost(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddPostRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 post 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/UpdatePost", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdatePostResponse UpdatePost(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdatePostRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 post 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/DeletePost", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeletePostResponse DeletePost(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeletePostRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 postCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetPostByCode", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetPostByCodeResponse GetPostByCode(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetPostByCodeRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 emps 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/UpdateEmpRole", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpRoleResponse UpdateEmpRole(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpRoleRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 role 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/AddRole", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddRoleResponse AddRole(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddRoleRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 role 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/DeleteRole", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteRoleResponse DeleteRole(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteRoleRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 roleCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetRoleByCode", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByCodeResponse GetRoleByCode(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByCodeRequest request);
        
        // CODEGEN: 命名空间 http://think3.com/ 的元素名称 roleName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetRoleByName", ReplyAction="*")]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByNameResponse GetRoleByName(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/SyncXMLData", ReplyAction="*")]
        bool SyncXMLData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/GetIsAutoSyncXMLData", ReplyAction="*")]
        bool GetIsAutoSyncXMLData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://think3.com/SetAutoSyncXMLDataFlag", ReplyAction="*")]
        bool SetAutoSyncXMLDataFlag(bool IsAutoSyncFlag);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrg", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddOrgRequestBody Body;
        
        public AddOrgRequest() {
        }
        
        public AddOrgRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddOrgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class AddOrgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parentOrgCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.OpeOrg org;
        
        public AddOrgRequestBody() {
        }
        
        public AddOrgRequestBody(string parentOrgCode, PortalIntegrationConsole.KBOrgUserSyncDataSrv.OpeOrg org) {
            this.parentOrgCode = parentOrgCode;
            this.org = org;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrgResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddOrgResponseBody Body;
        
        public AddOrgResponse() {
        }
        
        public AddOrgResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddOrgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class AddOrgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb AddOrgResult;
        
        public AddOrgResponseBody() {
        }
        
        public AddOrgResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb AddOrgResult) {
            this.AddOrgResult = AddOrgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrg", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateOrgRequestBody Body;
        
        public UpdateOrgRequest() {
        }
        
        public UpdateOrgRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateOrgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class UpdateOrgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.OpeOrg org;
        
        public UpdateOrgRequestBody() {
        }
        
        public UpdateOrgRequestBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.OpeOrg org) {
            this.org = org;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrgResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateOrgResponseBody Body;
        
        public UpdateOrgResponse() {
        }
        
        public UpdateOrgResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateOrgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class UpdateOrgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb UpdateOrgResult;
        
        public UpdateOrgResponseBody() {
        }
        
        public UpdateOrgResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb UpdateOrgResult) {
            this.UpdateOrgResult = UpdateOrgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOrgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteOrg", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteOrgRequestBody Body;
        
        public DeleteOrgRequest() {
        }
        
        public DeleteOrgRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteOrgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class DeleteOrgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.OpeOrg org;
        
        public DeleteOrgRequestBody() {
        }
        
        public DeleteOrgRequestBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.OpeOrg org) {
            this.org = org;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOrgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteOrgResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteOrgResponseBody Body;
        
        public DeleteOrgResponse() {
        }
        
        public DeleteOrgResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteOrgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class DeleteOrgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb DeleteOrgResult;
        
        public DeleteOrgResponseBody() {
        }
        
        public DeleteOrgResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb DeleteOrgResult) {
            this.DeleteOrgResult = DeleteOrgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetOrgInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetOrgInfo", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.SetOrgInfoRequestBody Body;
        
        public SetOrgInfoRequest() {
        }
        
        public SetOrgInfoRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.SetOrgInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class SetOrgInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orgCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int flag;
        
        public SetOrgInfoRequestBody() {
        }
        
        public SetOrgInfoRequestBody(string orgCode, int flag) {
            this.orgCode = orgCode;
            this.flag = flag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetOrgInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetOrgInfoResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.SetOrgInfoResponseBody Body;
        
        public SetOrgInfoResponse() {
        }
        
        public SetOrgInfoResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.SetOrgInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class SetOrgInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb SetOrgInfoResult;
        
        public SetOrgInfoResponseBody() {
        }
        
        public SetOrgInfoResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb SetOrgInfoResult) {
            this.SetOrgInfoResult = SetOrgInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrgByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrgByCode", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetOrgByCodeRequestBody Body;
        
        public GetOrgByCodeRequest() {
        }
        
        public GetOrgByCodeRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetOrgByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class GetOrgByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orgCode;
        
        public GetOrgByCodeRequestBody() {
        }
        
        public GetOrgByCodeRequestBody(string orgCode) {
            this.orgCode = orgCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrgByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrgByCodeResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetOrgByCodeResponseBody Body;
        
        public GetOrgByCodeResponse() {
        }
        
        public GetOrgByCodeResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetOrgByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class GetOrgByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.OpeOrg GetOrgByCodeResult;
        
        public GetOrgByCodeResponseBody() {
        }
        
        public GetOrgByCodeResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.OpeOrg GetOrgByCodeResult) {
            this.GetOrgByCodeResult = GetOrgByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.User user;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class AddUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb AddUserResult;
        
        public AddUserResponseBody() {
        }
        
        public AddUserResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb AddUserResult) {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUser", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateUserRequestBody Body;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class UpdateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.User user;
        
        public UpdateUserRequestBody() {
        }
        
        public UpdateUserRequestBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateUserResponseBody Body;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class UpdateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb UpdateUserResult;
        
        public UpdateUserResponseBody() {
        }
        
        public UpdateUserResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb UpdateUserResult) {
            this.UpdateUserResult = UpdateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUser", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteUserRequestBody Body;
        
        public DeleteUserRequest() {
        }
        
        public DeleteUserRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class DeleteUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userCode;
        
        public DeleteUserRequestBody() {
        }
        
        public DeleteUserRequestBody(string userCode) {
            this.userCode = userCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteUserResponseBody Body;
        
        public DeleteUserResponse() {
        }
        
        public DeleteUserResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class DeleteUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb DeleteUserResult;
        
        public DeleteUserResponseBody() {
        }
        
        public DeleteUserResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb DeleteUserResult) {
            this.DeleteUserResult = DeleteUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByCode", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetUserByCodeRequestBody Body;
        
        public GetUserByCodeRequest() {
        }
        
        public GetUserByCodeRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetUserByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class GetUserByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userCode;
        
        public GetUserByCodeRequestBody() {
        }
        
        public GetUserByCodeRequestBody(string userCode) {
            this.userCode = userCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByCodeResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetUserByCodeResponseBody Body;
        
        public GetUserByCodeResponse() {
        }
        
        public GetUserByCodeResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetUserByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class GetUserByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.User GetUserByCodeResult;
        
        public GetUserByCodeResponseBody() {
        }
        
        public GetUserByCodeResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.User GetUserByCodeResult) {
            this.GetUserByCodeResult = GetUserByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmpPostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmpPost", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpPostRequestBody Body;
        
        public UpdateEmpPostRequest() {
        }
        
        public UpdateEmpPostRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpPostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class UpdateEmpPostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string emps;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userCode;
        
        public UpdateEmpPostRequestBody() {
        }
        
        public UpdateEmpPostRequestBody(string emps, string userCode) {
            this.emps = emps;
            this.userCode = userCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmpPostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmpPostResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpPostResponseBody Body;
        
        public UpdateEmpPostResponse() {
        }
        
        public UpdateEmpPostResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpPostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class UpdateEmpPostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateEmpPostResult;
        
        public UpdateEmpPostResponseBody() {
        }
        
        public UpdateEmpPostResponseBody(string UpdateEmpPostResult) {
            this.UpdateEmpPostResult = UpdateEmpPostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPost", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddPostRequestBody Body;
        
        public AddPostRequest() {
        }
        
        public AddPostRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddPostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class AddPostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orgCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.Post post;
        
        public AddPostRequestBody() {
        }
        
        public AddPostRequestBody(string orgCode, PortalIntegrationConsole.KBOrgUserSyncDataSrv.Post post) {
            this.orgCode = orgCode;
            this.post = post;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPostResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddPostResponseBody Body;
        
        public AddPostResponse() {
        }
        
        public AddPostResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddPostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class AddPostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb AddPostResult;
        
        public AddPostResponseBody() {
        }
        
        public AddPostResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb AddPostResult) {
            this.AddPostResult = AddPostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePost", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdatePostRequestBody Body;
        
        public UpdatePostRequest() {
        }
        
        public UpdatePostRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdatePostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class UpdatePostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.Post post;
        
        public UpdatePostRequestBody() {
        }
        
        public UpdatePostRequestBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.Post post) {
            this.post = post;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePostResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdatePostResponseBody Body;
        
        public UpdatePostResponse() {
        }
        
        public UpdatePostResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdatePostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class UpdatePostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb UpdatePostResult;
        
        public UpdatePostResponseBody() {
        }
        
        public UpdatePostResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb UpdatePostResult) {
            this.UpdatePostResult = UpdatePostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePost", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeletePostRequestBody Body;
        
        public DeletePostRequest() {
        }
        
        public DeletePostRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeletePostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class DeletePostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.Post post;
        
        public DeletePostRequestBody() {
        }
        
        public DeletePostRequestBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.Post post) {
            this.post = post;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePostResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeletePostResponseBody Body;
        
        public DeletePostResponse() {
        }
        
        public DeletePostResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeletePostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class DeletePostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb DeletePostResult;
        
        public DeletePostResponseBody() {
        }
        
        public DeletePostResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb DeletePostResult) {
            this.DeletePostResult = DeletePostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostByCode", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetPostByCodeRequestBody Body;
        
        public GetPostByCodeRequest() {
        }
        
        public GetPostByCodeRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetPostByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class GetPostByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string postCode;
        
        public GetPostByCodeRequestBody() {
        }
        
        public GetPostByCodeRequestBody(string postCode) {
            this.postCode = postCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostByCodeResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetPostByCodeResponseBody Body;
        
        public GetPostByCodeResponse() {
        }
        
        public GetPostByCodeResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetPostByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class GetPostByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.Post GetPostByCodeResult;
        
        public GetPostByCodeResponseBody() {
        }
        
        public GetPostByCodeResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.Post GetPostByCodeResult) {
            this.GetPostByCodeResult = GetPostByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmpRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmpRole", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpRoleRequestBody Body;
        
        public UpdateEmpRoleRequest() {
        }
        
        public UpdateEmpRoleRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpRoleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class UpdateEmpRoleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string emps;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string posiCode;
        
        public UpdateEmpRoleRequestBody() {
        }
        
        public UpdateEmpRoleRequestBody(string emps, string posiCode) {
            this.emps = emps;
            this.posiCode = posiCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmpRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmpRoleResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpRoleResponseBody Body;
        
        public UpdateEmpRoleResponse() {
        }
        
        public UpdateEmpRoleResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpRoleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class UpdateEmpRoleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateEmpRoleResult;
        
        public UpdateEmpRoleResponseBody() {
        }
        
        public UpdateEmpRoleResponseBody(string UpdateEmpRoleResult) {
            this.UpdateEmpRoleResult = UpdateEmpRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRole", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddRoleRequestBody Body;
        
        public AddRoleRequest() {
        }
        
        public AddRoleRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddRoleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class AddRoleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.Role role;
        
        public AddRoleRequestBody() {
        }
        
        public AddRoleRequestBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.Role role) {
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRoleResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddRoleResponseBody Body;
        
        public AddRoleResponse() {
        }
        
        public AddRoleResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddRoleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class AddRoleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb AddRoleResult;
        
        public AddRoleResponseBody() {
        }
        
        public AddRoleResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb AddRoleResult) {
            this.AddRoleResult = AddRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteRole", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteRoleRequestBody Body;
        
        public DeleteRoleRequest() {
        }
        
        public DeleteRoleRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteRoleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class DeleteRoleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.Role role;
        
        public DeleteRoleRequestBody() {
        }
        
        public DeleteRoleRequestBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.Role role) {
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteRoleResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteRoleResponseBody Body;
        
        public DeleteRoleResponse() {
        }
        
        public DeleteRoleResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteRoleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class DeleteRoleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb DeleteRoleResult;
        
        public DeleteRoleResponseBody() {
        }
        
        public DeleteRoleResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb DeleteRoleResult) {
            this.DeleteRoleResult = DeleteRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoleByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoleByCode", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByCodeRequestBody Body;
        
        public GetRoleByCodeRequest() {
        }
        
        public GetRoleByCodeRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class GetRoleByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string roleCode;
        
        public GetRoleByCodeRequestBody() {
        }
        
        public GetRoleByCodeRequestBody(string roleCode) {
            this.roleCode = roleCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoleByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoleByCodeResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByCodeResponseBody Body;
        
        public GetRoleByCodeResponse() {
        }
        
        public GetRoleByCodeResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class GetRoleByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.Role GetRoleByCodeResult;
        
        public GetRoleByCodeResponseBody() {
        }
        
        public GetRoleByCodeResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.Role GetRoleByCodeResult) {
            this.GetRoleByCodeResult = GetRoleByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoleByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoleByName", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByNameRequestBody Body;
        
        public GetRoleByNameRequest() {
        }
        
        public GetRoleByNameRequest(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class GetRoleByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string roleName;
        
        public GetRoleByNameRequestBody() {
        }
        
        public GetRoleByNameRequestBody(string roleName) {
            this.roleName = roleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoleByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoleByNameResponse", Namespace="http://think3.com/", Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByNameResponseBody Body;
        
        public GetRoleByNameResponse() {
        }
        
        public GetRoleByNameResponse(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://think3.com/")]
    public partial class GetRoleByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.Role GetRoleByNameResult;
        
        public GetRoleByNameResponseBody() {
        }
        
        public GetRoleByNameResponseBody(PortalIntegrationConsole.KBOrgUserSyncDataSrv.Role GetRoleByNameResult) {
            this.GetRoleByNameResult = GetRoleByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface OrgUserSyncDataSrvSoapChannel : PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OrgUserSyncDataSrvSoapClient : System.ServiceModel.ClientBase<PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap>, PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap {
        
        public OrgUserSyncDataSrvSoapClient() {
        }
        
        public OrgUserSyncDataSrvSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrgUserSyncDataSrvSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrgUserSyncDataSrvSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrgUserSyncDataSrvSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddOrgResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.AddOrg(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddOrgRequest request) {
            return base.Channel.AddOrg(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb AddOrg(string parentOrgCode, PortalIntegrationConsole.KBOrgUserSyncDataSrv.OpeOrg org) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddOrgRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddOrgRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddOrgRequestBody();
            inValue.Body.parentOrgCode = parentOrgCode;
            inValue.Body.org = org;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddOrgResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).AddOrg(inValue);
            return retVal.Body.AddOrgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateOrgResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.UpdateOrg(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateOrgRequest request) {
            return base.Channel.UpdateOrg(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb UpdateOrg(PortalIntegrationConsole.KBOrgUserSyncDataSrv.OpeOrg org) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateOrgRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateOrgRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateOrgRequestBody();
            inValue.Body.org = org;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateOrgResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).UpdateOrg(inValue);
            return retVal.Body.UpdateOrgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteOrgResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.DeleteOrg(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteOrgRequest request) {
            return base.Channel.DeleteOrg(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb DeleteOrg(PortalIntegrationConsole.KBOrgUserSyncDataSrv.OpeOrg org) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteOrgRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteOrgRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteOrgRequestBody();
            inValue.Body.org = org;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteOrgResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).DeleteOrg(inValue);
            return retVal.Body.DeleteOrgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.SetOrgInfoResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.SetOrgInfo(PortalIntegrationConsole.KBOrgUserSyncDataSrv.SetOrgInfoRequest request) {
            return base.Channel.SetOrgInfo(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb SetOrgInfo(string orgCode, int flag) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.SetOrgInfoRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.SetOrgInfoRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.SetOrgInfoRequestBody();
            inValue.Body.orgCode = orgCode;
            inValue.Body.flag = flag;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.SetOrgInfoResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).SetOrgInfo(inValue);
            return retVal.Body.SetOrgInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetOrgByCodeResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.GetOrgByCode(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetOrgByCodeRequest request) {
            return base.Channel.GetOrgByCode(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.OpeOrg GetOrgByCode(string orgCode) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetOrgByCodeRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetOrgByCodeRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetOrgByCodeRequestBody();
            inValue.Body.orgCode = orgCode;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetOrgByCodeResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).GetOrgByCode(inValue);
            return retVal.Body.GetOrgByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddUserResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.AddUser(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb AddUser(PortalIntegrationConsole.KBOrgUserSyncDataSrv.User user) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddUserRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddUserRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddUserRequestBody();
            inValue.Body.user = user;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddUserResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).AddUser(inValue);
            return retVal.Body.AddUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateUserResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.UpdateUser(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb UpdateUser(PortalIntegrationConsole.KBOrgUserSyncDataSrv.User user) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateUserRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateUserRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateUserRequestBody();
            inValue.Body.user = user;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateUserResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).UpdateUser(inValue);
            return retVal.Body.UpdateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteUserResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.DeleteUser(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteUserRequest request) {
            return base.Channel.DeleteUser(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb DeleteUser(string userCode) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteUserRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteUserRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteUserRequestBody();
            inValue.Body.userCode = userCode;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteUserResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).DeleteUser(inValue);
            return retVal.Body.DeleteUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetUserByCodeResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.GetUserByCode(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetUserByCodeRequest request) {
            return base.Channel.GetUserByCode(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.User GetUserByCode(string userCode) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetUserByCodeRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetUserByCodeRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetUserByCodeRequestBody();
            inValue.Body.userCode = userCode;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetUserByCodeResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).GetUserByCode(inValue);
            return retVal.Body.GetUserByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpPostResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.UpdateEmpPost(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpPostRequest request) {
            return base.Channel.UpdateEmpPost(request);
        }
        
        public string UpdateEmpPost(string emps, string userCode) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpPostRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpPostRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpPostRequestBody();
            inValue.Body.emps = emps;
            inValue.Body.userCode = userCode;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpPostResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).UpdateEmpPost(inValue);
            return retVal.Body.UpdateEmpPostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddPostResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.AddPost(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddPostRequest request) {
            return base.Channel.AddPost(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb AddPost(string orgCode, PortalIntegrationConsole.KBOrgUserSyncDataSrv.Post post) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddPostRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddPostRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddPostRequestBody();
            inValue.Body.orgCode = orgCode;
            inValue.Body.post = post;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddPostResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).AddPost(inValue);
            return retVal.Body.AddPostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdatePostResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.UpdatePost(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdatePostRequest request) {
            return base.Channel.UpdatePost(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb UpdatePost(PortalIntegrationConsole.KBOrgUserSyncDataSrv.Post post) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdatePostRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdatePostRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdatePostRequestBody();
            inValue.Body.post = post;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdatePostResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).UpdatePost(inValue);
            return retVal.Body.UpdatePostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeletePostResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.DeletePost(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeletePostRequest request) {
            return base.Channel.DeletePost(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb DeletePost(PortalIntegrationConsole.KBOrgUserSyncDataSrv.Post post) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeletePostRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeletePostRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeletePostRequestBody();
            inValue.Body.post = post;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeletePostResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).DeletePost(inValue);
            return retVal.Body.DeletePostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetPostByCodeResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.GetPostByCode(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetPostByCodeRequest request) {
            return base.Channel.GetPostByCode(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.Post GetPostByCode(string postCode) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetPostByCodeRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetPostByCodeRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetPostByCodeRequestBody();
            inValue.Body.postCode = postCode;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetPostByCodeResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).GetPostByCode(inValue);
            return retVal.Body.GetPostByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpRoleResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.UpdateEmpRole(PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpRoleRequest request) {
            return base.Channel.UpdateEmpRole(request);
        }
        
        public string UpdateEmpRole(string emps, string posiCode) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpRoleRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpRoleRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpRoleRequestBody();
            inValue.Body.emps = emps;
            inValue.Body.posiCode = posiCode;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.UpdateEmpRoleResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).UpdateEmpRole(inValue);
            return retVal.Body.UpdateEmpRoleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddRoleResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.AddRole(PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddRoleRequest request) {
            return base.Channel.AddRole(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb AddRole(PortalIntegrationConsole.KBOrgUserSyncDataSrv.Role role) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddRoleRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddRoleRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddRoleRequestBody();
            inValue.Body.role = role;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.AddRoleResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).AddRole(inValue);
            return retVal.Body.AddRoleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteRoleResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.DeleteRole(PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteRoleRequest request) {
            return base.Channel.DeleteRole(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.RetOb DeleteRole(PortalIntegrationConsole.KBOrgUserSyncDataSrv.Role role) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteRoleRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteRoleRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteRoleRequestBody();
            inValue.Body.role = role;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.DeleteRoleResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).DeleteRole(inValue);
            return retVal.Body.DeleteRoleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByCodeResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.GetRoleByCode(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByCodeRequest request) {
            return base.Channel.GetRoleByCode(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.Role GetRoleByCode(string roleCode) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByCodeRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByCodeRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByCodeRequestBody();
            inValue.Body.roleCode = roleCode;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByCodeResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).GetRoleByCode(inValue);
            return retVal.Body.GetRoleByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByNameResponse PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap.GetRoleByName(PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByNameRequest request) {
            return base.Channel.GetRoleByName(request);
        }
        
        public PortalIntegrationConsole.KBOrgUserSyncDataSrv.Role GetRoleByName(string roleName) {
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByNameRequest inValue = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByNameRequest();
            inValue.Body = new PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByNameRequestBody();
            inValue.Body.roleName = roleName;
            PortalIntegrationConsole.KBOrgUserSyncDataSrv.GetRoleByNameResponse retVal = ((PortalIntegrationConsole.KBOrgUserSyncDataSrv.OrgUserSyncDataSrvSoap)(this)).GetRoleByName(inValue);
            return retVal.Body.GetRoleByNameResult;
        }
        
        public bool SyncXMLData() {
            return base.Channel.SyncXMLData();
        }
        
        public bool GetIsAutoSyncXMLData() {
            return base.Channel.GetIsAutoSyncXMLData();
        }
        
        public bool SetAutoSyncXMLDataFlag(bool IsAutoSyncFlag) {
            return base.Channel.SetAutoSyncXMLDataFlag(IsAutoSyncFlag);
        }
    }
}
